# This database is used for local development and testing purposes only.
services:
  db1:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'bounties'
      POSTGRES_USER: '2077'
      POSTGRES_PASSWORD: '2077'
    ports:
      - '5432:5432'

  db2:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'test_bounties'
      POSTGRES_USER: '2077'
      POSTGRES_PASSWORD: '2077'
    ports:
      - '5433:5432'
