#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running format check..."
npm run format || 
{
    echo 'Formatting failed. Please run "npm run format" and fix the issues before committing.'
    exit 1
}

# echo "Running linter..."
# npm run lint ||
# {
#     echo 'Linting failed. Please run "npm run lint" and fix the issues before committing.'
#     exit 1
# }

# If everything passes, proceed with the commit
exit 0
