name: Run Tests and Prevent Merge

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: 'supersecret'
      DATABASE_URL: 'postgresql://postgres:password@localhost:5433/test'
      DATABASE_CONNECTION_URL: 'postgresql://2077:2077@localhost:5433/test_bounties'
      NODE_ENV: 'test'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust this to your project's Node.js version

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Specify the pnpm version you want to use

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm run check

      - name: Lint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run integration tests
        run: pnpm run test:integration

      - name: Check test results
        if: failure()
        run: |
          echo "Tests failed. This pull request cannot be merged to main."
          exit 1
